### PR TITLE
Support virtualTextDocument transparently by BufReadCmd

### PR DESCRIPTION
**Pull request by hrsh7th**
This PR aims to support virtualTextDocument by BufReadCmd autocmd.

You can jump to the definition via just invoking `vim.lsp.buf.definition` method after call `require('deno-nvim').setup()`.

### CODE REVIEW

**Comment by sigmaSd** [comment]
Hello @hrsh7th thanks for your interest in this plugin

I understand since you opened the PR I should just merge immediatly xD

Just one question, can you elaborate, on what does this PR add, was there something not working that this pr fixes ?

**Comment by sigmaSd** [comment]
So from what I understand, this is  using BufReadCmd to replace overriding handlers  in lspconfig https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/denols.lua#L76

In that case I think this PR belongs there, I tested your modification there and it does work as expected (with some minor modification to the handler)

**Comment by sigmaSd** [comment]
The virtual handler in this plugin do not handle gotodef and references (those are in lspconfig), but it handles deno  commands like performance and status

**Comment by hrsh7th** [comment]
It allows to jump to the remote file :)


https://user-images.githubusercontent.com/629908/208925978-3b1beda9-82f2-4327-9da4-216de849c985.mov

**Comment by sigmaSd** [comment]
Weird jumping to a remote file should be already handled

Please open your pr in lspconfig, I think you need to remove these custom handlers https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/denols.lua#L76 and add the autocmd there

And also consider  opening a separate issue on this repo regarding the jump to remote files (it works on my end without this patch)

**Comment by sigmaSd** [comment]
Actually the issue should also be opened against lspconfig, since this plugin is not needed for gotodefintion (to remote files) to work

**Comment by hrsh7th** [comment]
OK. Sorry. I didn't know lspconfig has already implemented the feature.

In my case, I use client.request method directly so the response didn't handled by default handlers.

Hm... I think this PR should be closed for now. Thank you for your response.

**Comment by sigmaSd** [comment]
Feel free to raise an issue if it still doesn't work correctly or if you have a use case that we don't support yet

**Pull request closed without merging**
